#
# One stanza per hostname.
#
magicbook:
  method: ssh
  hostname: raptor.austin.ibm.com
  username: condor
  path: /gsa/ausgsa/projects/a/aix_tools/bin/cmvc

raptor:
  method: local
  path: /gsa/ausgsa/projects/a/aix_tools/bin/cmvc
