#  -*- coding: utf-8 -*-
# 
#  Copyright 2012-2013 Ease Software, Inc. and Perry Smith
#  All Rights Reserved
# 
#
# One stanza per hostname.
#
magicbook:
  method: ssh
  hostname: raptor.austin.ibm.com
  username: condor
  path: /gsa/ausgsa/projects/a/aix_tools/bin/cmvc
  bootstrap_cmvc_user: pedzan

#   method: local
#   path: /Users/pedzan/Source/Rails3/condor3

raptor:
  method: local
  path: /gsa/ausgsa/projects/a/aix_tools/bin/cmvc
  bootstrap_cmvc_user: pedzan
