#  -*- coding: utf-8 -*-
# 
#  Copyright 2012-2013 Ease Software, Inc. and Perry Smith
#  All Rights Reserved
# 
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: condor3_development
  pool: 5

template:
  adapter: postgresql
  encoding: unicode
  database: condor3_template

test: &test
  adapter: postgresql
  template: condor3_template
  encoding: unicode
  database: condor3_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: condor3_production
  pool: 5

cucumber:
  <<: *test
