#  -*- coding: utf-8 -*-
# 
#  Copyright 2012-2013 Ease Software, Inc. and Perry Smith
#  All Rights Reserved
# 
development:
  host: bluepages.ibm.com
  port: 389
  base: o=ibm.com
  # base: ou=bluepages,o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret

staging:
  host: bluepages.ibm.com
  port: 389
  base: o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret

test:
  host: bluepages.ibm.com
  port: 389
  base: o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret

production:
  host: bluepages.ibm.com
  port: 389
  base: o=ibm.com
  # port: 636
  # method: :ssl
  # bind_dn: cn=admin,dc=local,dc=net
  # password: secret
